/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as AuthSigninIndexRouteImport } from './routes/auth/signin/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninIndexRoute = AuthSigninIndexRouteImport.update({
  id: '/auth/signin/',
  path: '/auth/signin/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/groups': typeof GroupsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/runs': typeof RunsIndexRoute
  '/auth/signin': typeof AuthSigninIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/groups': typeof GroupsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/runs': typeof RunsIndexRoute
  '/auth/signin': typeof AuthSigninIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/groups/': typeof GroupsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/auth/signin/': typeof AuthSigninIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/groups' | '/profile' | '/runs' | '/auth/signin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/groups' | '/profile' | '/runs' | '/auth/signin'
  id: '__root__' | '/' | '/groups/' | '/profile/' | '/runs/' | '/auth/signin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
  AuthSigninIndexRoute: typeof AuthSigninIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin/': {
      id: '/auth/signin/'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
  AuthSigninIndexRoute: AuthSigninIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
