/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as EventsEventIdRouteImport } from './routes/events/$eventId'
import { Route as EventsNewIndexRouteImport } from './routes/events/new/index'
import { Route as EventsJoinIndexRouteImport } from './routes/events/join/index'
import { Route as AuthSigninIndexRouteImport } from './routes/auth/signin/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsNewIndexRoute = EventsNewIndexRouteImport.update({
  id: '/events/new/',
  path: '/events/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsJoinIndexRoute = EventsJoinIndexRouteImport.update({
  id: '/events/join/',
  path: '/events/join/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSigninIndexRoute = AuthSigninIndexRouteImport.update({
  id: '/auth/signin/',
  path: '/auth/signin/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events': typeof EventsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/runs': typeof RunsIndexRoute
  '/auth/signin': typeof AuthSigninIndexRoute
  '/events/join': typeof EventsJoinIndexRoute
  '/events/new': typeof EventsNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events': typeof EventsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/runs': typeof RunsIndexRoute
  '/auth/signin': typeof AuthSigninIndexRoute
  '/events/join': typeof EventsJoinIndexRoute
  '/events/new': typeof EventsNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/events/': typeof EventsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/auth/signin/': typeof AuthSigninIndexRoute
  '/events/join/': typeof EventsJoinIndexRoute
  '/events/new/': typeof EventsNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events/$eventId'
    | '/events'
    | '/profile'
    | '/runs'
    | '/auth/signin'
    | '/events/join'
    | '/events/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events/$eventId'
    | '/events'
    | '/profile'
    | '/runs'
    | '/auth/signin'
    | '/events/join'
    | '/events/new'
  id:
    | '__root__'
    | '/'
    | '/events/$eventId'
    | '/events/'
    | '/profile/'
    | '/runs/'
    | '/auth/signin/'
    | '/events/join/'
    | '/events/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
  AuthSigninIndexRoute: typeof AuthSigninIndexRoute
  EventsJoinIndexRoute: typeof EventsJoinIndexRoute
  EventsNewIndexRoute: typeof EventsNewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/new/': {
      id: '/events/new/'
      path: '/events/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/join/': {
      id: '/events/join/'
      path: '/events/join'
      fullPath: '/events/join'
      preLoaderRoute: typeof EventsJoinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/signin/': {
      id: '/auth/signin/'
      path: '/auth/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  EventsIndexRoute: EventsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
  AuthSigninIndexRoute: AuthSigninIndexRoute,
  EventsJoinIndexRoute: EventsJoinIndexRoute,
  EventsNewIndexRoute: EventsNewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
