name: Debug Android Build and Distribute

on:
  push:
    branches:
      - main
    paths:
      - apps/app/package.json
  workflow_dispatch:

jobs:
  debug-build:
    name: Debug Build and Distribute
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      # 2. バージョン変更を確認
      - name: Check for version change
        id: version_check
        run: |
          git fetch --depth=2
          OLD_VERSION=$(git show HEAD~1:apps/app/package.json | jq -r .version)
          NEW_VERSION=$(jq -r .version < apps/app/package.json)
          echo "Old Version: $OLD_VERSION"
          echo "New Version: $NEW_VERSION"
          if [ "$OLD_VERSION" = "$NEW_VERSION" ]; then
            echo "No version change detected"
            exit 1
          fi
        shell: bash

      # 以下は他のステップ...
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.11.0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.14.2

      - name: Install dependencies
        run: pnpm install

      - name: Build Web and Dependencies
        run: pnpm build

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: 34.0.0

      - name: Build Debug APK
        run: |
          cd apps/app/android
          ./gradlew assembleDebug

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Distribute to Firebase App Distribution
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase appdistribution:distribute \
            apps/app/android/app/build/outputs/apk/debug/app-debug.apk \
            --app 1:912731691279:android:0849183bb9ee23c66d867a \
            --groups developer

      # Discord に通知
      - name: Notify Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
